version: '3.8'

services:
  app:
    image: laravelsail/php82-composer
    container_name: vetclinic_app
    restart: unless-stopped
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
      - mailpit
    environment:
      - WWWGROUP=${WWWGROUP}
      - WWWUSER=${WWWUSER}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=vetclinic
      - DB_USERNAME=vetclinic_user
      - DB_PASSWORD=vetclinic_password

  mysql:
    image: mysql:8.0
    container_name: vetclinic_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vetclinic
      MYSQL_USER: vetclinic_user
      MYSQL_PASSWORD: vetclinic_password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: vetclinic_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: vetclinic_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"

  adminer:
    image: adminer
    container_name: vetclinic_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql_data:
